// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLatestRelease() {
  return window['go']['main']['App']['CheckLatestRelease']();
}

export function CreateTunnel(arg1) {
  return window['go']['main']['App']['CreateTunnel'](arg1);
}

export function DeleteDNSByName(arg1, arg2) {
  return window['go']['main']['App']['DeleteDNSByName'](arg1, arg2);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function EnsureCNAME(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnsureCNAME'](arg1, arg2, arg3);
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetIngressConfig(arg1) {
  return window['go']['main']['App']['GetIngressConfig'](arg1);
}

export function GetRunStates() {
  return window['go']['main']['App']['GetRunStates']();
}

export function GetTunnelDetail(arg1) {
  return window['go']['main']['App']['GetTunnelDetail'](arg1);
}

export function GetTunnelToken(arg1) {
  return window['go']['main']['App']['GetTunnelToken'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListDNSRecords(arg1) {
  return window['go']['main']['App']['ListDNSRecords'](arg1);
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function ListZones() {
  return window['go']['main']['App']['ListZones']();
}

export function LogDir() {
  return window['go']['main']['App']['LogDir']();
}

export function OpenLogDir() {
  return window['go']['main']['App']['OpenLogDir']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function RestoreRunning() {
  return window['go']['main']['App']['RestoreRunning']();
}

export function RetryVerify() {
  return window['go']['main']['App']['RetryVerify']();
}

export function SaveIngressConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveIngressConfig'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopAllTunnels() {
  return window['go']['main']['App']['StopAllTunnels']();
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function VerifyAndSaveToken(arg1) {
  return window['go']['main']['App']['VerifyAndSaveToken'](arg1);
}

export function WriteOpLog(arg1, arg2) {
  return window['go']['main']['App']['WriteOpLog'](arg1, arg2);
}
