// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cloudflare} from '../models';
import {auth} from '../models';

export function CreateTunnel(arg1:string):Promise<cloudflare.Tunnel>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function GetAuthState():Promise<auth.State>;

export function GetRunStates():Promise<Record<string, string>>;

export function GetTunnelDetail(arg1:string):Promise<cloudflare.TunnelDetail>;

export function GetTunnelToken(arg1:string):Promise<string>;

export function ListTunnels():Promise<Array<cloudflare.Tunnel>>;

export function RetryVerify():Promise<cloudflare.TokenInfo>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopAllTunnels():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function VerifyAndSaveToken(arg1:string):Promise<cloudflare.TokenInfo>;
