// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function RetryVerify() {
  return window['go']['main']['App']['RetryVerify']();
}

export function VerifyAndSaveToken(arg1) {
  return window['go']['main']['App']['VerifyAndSaveToken'](arg1);
}
