// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {cloudflare} from '../models';

export function GetAuthState():Promise<auth.State>;

export function ListTunnels():Promise<Array<cloudflare.Tunnel>>;

export function RetryVerify():Promise<cloudflare.TokenInfo>;

export function VerifyAndSaveToken(arg1:string):Promise<cloudflare.TokenInfo>;
