// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cloudflare} from '../models';
import {auth} from '../models';

export function CreateTunnel(arg1:string):Promise<cloudflare.Tunnel>;

export function DeleteDNSByName(arg1:string,arg2:string):Promise<boolean>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function EnsureCNAME(arg1:string,arg2:string,arg3:string):Promise<cloudflare.DNSEnsureResult>;

export function GetAuthState():Promise<auth.State>;

export function GetIngressConfig(arg1:string):Promise<Array<cloudflare.IngressRule>>;

export function GetRunStates():Promise<Record<string, string>>;

export function GetTunnelDetail(arg1:string):Promise<cloudflare.TunnelDetail>;

export function GetTunnelToken(arg1:string):Promise<string>;

export function ListDNSRecords(arg1:string):Promise<Array<cloudflare.DNSRecord>>;

export function ListTunnels():Promise<Array<cloudflare.Tunnel>>;

export function ListZones():Promise<Array<cloudflare.Zone>>;

export function LogDir():Promise<string>;

export function OpenLogDir():Promise<void>;

export function Quit():Promise<void>;

export function RetryVerify():Promise<cloudflare.TokenInfo>;

export function SaveIngressConfig(arg1:string,arg2:Array<cloudflare.IngressRule>):Promise<Array<cloudflare.IngressRule>>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopAllTunnels():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;

export function VerifyAndSaveToken(arg1:string):Promise<cloudflare.TokenInfo>;

export function WriteOpLog(arg1:string,arg2:string):Promise<void>;

export function GetServiceStatus():Promise<string>;
export function InstallService():Promise<void>;
export function UninstallService():Promise<void>;
export function StartService():Promise<void>;
export function StopService():Promise<void>;
